### ISSUE TITLE
ElasticPress versie 5.x

### ISSUE THREAD

**Issue by rmpel** [OpenWebconcept/plugin-openpub-base#23]
OpenPub Base plugin zet de requirement van ElasticPress op 4, resulterend in

"Your Elasticsearch version 7.17.8 is above the maximum required Elasticsearch version 7.10. ElasticPress may or may not work properly."

Versie 5.x heeft dit issue niet.

De keuze voor versie 4.x zal bewust zijn, wat is er nodig om naar 5.x te upgraden?

**Comment by mvdhoek1** [comment]
De verschillen tussen versie 4 en 5 lijken gering te zijn. Althans wat betreft de impact. 
We kunnen de [dep](https://github.com/OpenWebconcept/plugin-openpub-base/blob/master/composer.json#L30) wel aanpassen naar `"wpackagist-plugin/elasticpress": "^4.0 | ^5.0"` maar @SimonvanWijhe is de expert. Simon kun jij Remon verder helpen?
