### ISSUE TITLE
Unable to add themes

### ISSUE THREAD

**Issue by sanderdekroon** [OpenWebconcept/plugin-openpub-base#9]
In the `openpub-theme` post type the `public` option has been set to false, which means it does not show up in the admin menu. This makes it impossible for our editors to add a new theme. 

https://github.com/OpenWebconcept/plugin-openpub-base/blob/9877217ba70d773a9e1be5207365f71b1e0d9a8b/config/posttypes.php#L111

According to the code comment it's because of excluding the theme's from syncing with Elasticsearch. I'm left wondering how you add new themes? And might it be possible to exclude this/these posttype(s) from Elasticsearch through other means?

**Comment by sanderdekroon** [comment]
Anybody from @OpenWebconcept/yard-digital-agency who can comment on this?

**Comment by mvdhoek1** [comment]
Hi Sander, I'll take a look on monday. Busy week this week :)

**Comment by SimonvanWijhe** [comment]
Openpub items already have the taxonomies "Type", "Doelgroepen", "Toepassingen", and (optionally) "Tonen op". We started using those instead of post types some time ago.

**Comment by sanderdekroon** [comment]
Please don't deprecate them :). We're using them extensively to categorize openpub items and query 'related' openpub items to PDC themes.

But besides that, while you might not use them, I think this openpub-theme post type is consistent behaviour when compared to the OpenPDC. If it's alright with you, I will create a PR to update the `public` property.

**Comment by mvdhoek1** [comment]
@SimonvanWijhe, I believe we can set the status of `'public'` to `true`. We have additional settings in our own elasticsearch plugin which configures the indexable post_types.

**Comment by SimonvanWijhe** [comment]
No problem, we can just leave the extra post types in. 

It would be great if making these post type visible is optional. Since just changing `public` into `true` will make the post types visible in all our sites as well. And we don't want that.

@mvdhoek1 you are right, setting `public` to `true` does not effect elasticsearch anymore.

**Comment by mvdhoek1** [comment]
@sanderdekroon je kunt het doorvoeren. Dan voer ik het vandaag nog door.
